-- Configure Monkey Barrels (shared libraries) a project depends on.
--
-- Consuming a barrel takes two edits, matching the VS Code extension:
--   1. barrels.jungle: `<Module> = [<path>]` plus a line appending it to
--      base.barrelPath, so the compiler can find the barrel.
--   2. manifest.xml <iq:barrels>: `<iq:depends name="<Module>" version="..."/>`.
-- The module name and version are read from the barrel project's own manifest
-- (`<iq:barrel module="..." version="...">`). Paths are written relative to the
-- project when possible (portable), unlike the extension's absolute paths.

local sdk = require("garmin-monkeyc.sdk")

local M = {}

local JUNGLE_HEADER = "# Generated by garmin-monkeyc. Run :MonkeyC configure-barrel to change it.\n"

local function notify(message, level)
  vim.notify("garmin-monkeyc: " .. message, level or vim.log.levels.INFO)
end

local function project_directory()
  local root = vim.fs.root(0, { "manifest.xml", ".git" }) or vim.uv.cwd()

  return sdk.project_directory(root)
end

local function manifest_path()
  return vim.fs.joinpath(project_directory(), "manifest.xml")
end

local function barrels_jungle_path()
  return vim.fs.joinpath(project_directory(), "barrels.jungle")
end

local function read(path)
  return table.concat(vim.fn.readfile(path), "\n")
end

local function save(path, content)
  vim.fn.writefile(vim.split(content, "\n"), path)
  vim.cmd("checktime") -- reload the file if it is open in a buffer
end

-- Path to reference from barrels.jungle: relative to the project when both live
-- under a shared root (portable across machines), otherwise absolute.
local function jungle_reference_path(barrel_jungle)
  local base = vim.split(vim.fs.normalize(project_directory()), "/", { trimempty = true })
  local target = vim.split(vim.fs.normalize(barrel_jungle), "/", { trimempty = true })

  local shared = 0
  while base[shared + 1] and target[shared + 1] and base[shared + 1] == target[shared + 1] do
    shared = shared + 1
  end

  -- No common root (e.g. different Windows drive): keep it absolute.
  if shared == 0 then
    return barrel_jungle
  end

  local parts = {}
  for _ = shared + 1, #base do
    parts[#parts + 1] = ".."
  end
  for index = shared + 1, #target do
    parts[#parts + 1] = target[index]
  end

  return table.concat(parts, "/")
end

-- Read the barrel's module name and version from a barrel project, given a
-- directory, its monkey.jungle, or its manifest.xml. nil if it isn't a barrel.
local function barrel_project_info(input)
  input = vim.fn.expand(input)

  local jungle, manifest
  local stat = vim.uv.fs_stat(input)

  if stat and stat.type == "directory" then
    jungle = vim.fs.joinpath(input, "monkey.jungle")
    manifest = vim.fs.joinpath(input, "manifest.xml")
  elseif input:match("%.jungle$") then
    jungle = input
    manifest = vim.fs.joinpath(vim.fs.dirname(input), "manifest.xml")
  elseif input:match("manifest%.xml$") then
    manifest = input
    jungle = vim.fs.joinpath(vim.fs.dirname(input), "monkey.jungle")
  else
    return nil
  end

  if not (vim.uv.fs_stat(manifest) and vim.uv.fs_stat(jungle)) then
    return nil
  end

  local tag = read(manifest):match("<iq:barrel[^>]*>")
  if not tag then
    return nil
  end

  local module = tag:match('module="([^"]*)"')
  local version = tag:match('version="([^"]*)"')

  if not module or module == "" then
    return nil
  end

  return { module = module, version = version or "", jungle = jungle }
end

-- Barrel dependencies declared in the manifest (<iq:depends name version>).
local function manifest_barrels(content)
  local barrels = {}

  for tag in content:gmatch("<iq:depends[^>]*/>") do
    local name = tag:match('name="([^"]*)"')

    if name then
      barrels[#barrels + 1] = { name = name, version = tag:match('version="([^"]*)"') or "" }
    end
  end

  return barrels
end

-- Rewrite (or insert) the manifest's <iq:barrels> block.
local function set_manifest_barrels(path, barrels)
  local content = read(path)
  local indent = content:match("([ \t]*)<iq:barrels") or "        "
  local child = indent .. "    "

  local rendered = {}
  for _, barrel in ipairs(barrels) do
    rendered[#rendered + 1] = child .. ('<iq:depends name="%s" version="%s"/>'):format(barrel.name, barrel.version)
  end

  local block = "<iq:barrels>\n"
    .. table.concat(rendered, "\n")
    .. (#rendered > 0 and "\n" or "")
    .. indent
    .. "</iq:barrels>"

  local escaped = block:gsub("%%", "%%%%")
  local updated, replaced = content:gsub("<iq:barrels>.-</iq:barrels>", escaped, 1)

  if replaced == 0 then
    local insert = "\n" .. (indent .. block):gsub("%%", "%%%%") .. "%1"
    updated, replaced = content:gsub("(\n[ \t]*</iq:application>)", insert, 1)
  end

  if replaced == 0 then
    return notify("could not update <iq:barrels> in manifest.xml", vim.log.levels.ERROR)
  end

  save(path, updated)
end

-- Add (or update) a barrel entry in barrels.jungle.
local function add_to_jungle(module, path)
  local jungle = barrels_jungle_path()
  local content = vim.uv.fs_stat(jungle) and read(jungle) or JUNGLE_HEADER
  local entry = ("%s = [%s]"):format(module, path)

  if content:match("\n" .. module .. "%s*=") or content:match("^" .. module .. "%s*=") then
    -- Already listed: replace its path, leave the base.barrelPath line alone.
    content = content:gsub(module .. "%s*=%s*%[[^%]]*%]", (entry):gsub("%%", "%%%%"), 1)
  else
    if not content:match("\n$") then
      content = content .. "\n"
    end

    content = content .. entry .. "\n" .. ("base.barrelPath = $(base.barrelPath);$(%s)\n"):format(module)
  end

  save(jungle, content)
end

-- Remove a barrel's entry and its base.barrelPath line from barrels.jungle.
local function remove_from_jungle(module)
  local jungle = barrels_jungle_path()

  if not vim.uv.fs_stat(jungle) then
    return
  end

  local content = read(jungle)
  content = content:gsub("\n?" .. module .. "%s*=%s*%[[^%]]*%]", "")
  content = content:gsub("\n?base%.barrelPath%s*=%s*%$%(base%.barrelPath%);%$%(" .. module .. "%)", "")

  -- Nothing left to declare: drop the file rather than leave an empty stub.
  if not content:match("[%w_]+%s*=%s*%[") then
    vim.fn.delete(jungle)
    vim.cmd("checktime")

    return
  end

  save(jungle, content)
end

-- Barrel module -> path, as recorded in barrels.jungle (`<Module> = [<path>]`).
local function jungle_barrel_paths()
  local jungle = barrels_jungle_path()

  if not vim.uv.fs_stat(jungle) then
    return {}
  end

  local paths = {}
  for module, path in read(jungle):gmatch("([%w_]+)%s*=%s*%[([^%]]*)%]") do
    paths[module] = path
  end

  return paths
end

-- Add the barrel at the given path to both the manifest and barrels.jungle.
function M.add_barrel(input)
  local function apply(path_input)
    if not path_input or path_input == "" then
      return
    end

    local info = barrel_project_info(path_input)
    if not info then
      return notify("not a barrel project (no <iq:barrel module=…> manifest found)", vim.log.levels.ERROR)
    end

    local manifest = manifest_path()
    local barrels = manifest_barrels(read(manifest))
    local found = false

    for _, barrel in ipairs(barrels) do
      if barrel.name == info.module then
        barrel.version = info.version
        found = true
      end
    end

    if not found then
      barrels[#barrels + 1] = { name = info.module, version = info.version }
    end

    set_manifest_barrels(manifest, barrels)
    add_to_jungle(info.module, jungle_reference_path(info.jungle))
    notify(("%s barrel %s (%s)"):format(found and "updated" or "added", info.module, info.version))
  end

  if input and input ~= "" then
    return apply(input)
  end

  vim.ui.input({ prompt = "Barrel project (its monkey.jungle or directory): ", completion = "file" }, apply)
end

-- Re-read a known barrel's current version from its project (using the path
-- already recorded in barrels.jungle) and refresh the manifest and jungle.
function M.update_barrel(name)
  local path = jungle_barrel_paths()[name]

  if not path then
    return notify("no path recorded for barrel " .. name .. " in barrels.jungle", vim.log.levels.ERROR)
  end

  -- Recorded paths are relative to the project; resolve to open the barrel.
  if not path:match("^/") then
    path = vim.fs.normalize(vim.fs.joinpath(project_directory(), path))
  end

  M.add_barrel(path)
end

-- Remove a barrel dependency from the manifest and barrels.jungle.
function M.remove_barrel(name)
  local manifest = manifest_path()
  local kept = {}

  for _, barrel in ipairs(manifest_barrels(read(manifest))) do
    if barrel.name ~= name then
      kept[#kept + 1] = barrel
    end
  end

  set_manifest_barrels(manifest, kept)
  remove_from_jungle(name)
  notify("removed barrel " .. name)
end

-- Pick add or remove; the entry point for :MonkeyC configure-barrel.
function M.configure_barrel()
  local manifest = manifest_path()

  if not vim.uv.fs_stat(manifest) then
    return notify("no manifest.xml found", vim.log.levels.ERROR)
  end

  local barrels = manifest_barrels(read(manifest))
  local choices = { "Add a barrel" }
  local actions = {
    function()
      M.add_barrel()
    end,
  }

  for _, barrel in ipairs(barrels) do
    local name = barrel.name

    choices[#choices + 1] = ("Update %s (%s)"):format(name, barrel.version)
    actions[#actions + 1] = function()
      M.update_barrel(name)
    end

    choices[#choices + 1] = ("Remove %s"):format(name)
    actions[#actions + 1] = function()
      M.remove_barrel(name)
    end
  end

  vim.ui.select(choices, { prompt = "Configure Monkey Barrels" }, function(choice, index)
    if choice then
      actions[index]()
    end
  end)
end

return M
